--- a/makefile	2024-06-06 19:29:58.560198681 +0300
+++ b/makefile	2024-06-06 19:33:02.941420691 +0300
@@ -115,7 +115,7 @@
 
 
 ifeq ($(USE_AOT),true)
-	PUBLISHFLAGS ?=  -r $(MESENPLATFORM) -p:PublishSingleFile=false -p:PublishAot=true -p:SelfContained=true
+	PUBLISHFLAGS ?=  -r $(MESENPLATFORM) --source ../nuget-sources -p:PublishSingleFile=false -p:PublishAot=true -p:SelfContained=true
 else
 	PUBLISHFLAGS ?=  -r $(MESENPLATFORM) --no-self-contained true -p:PublishSingleFile=true
 endif
@@ -168,7 +168,7 @@
 	X11LIB :=
 endif
 
-FSLIB := -lstdc++fs
+FSLIB :=
 
 ifeq ($(MESENOS),osx)
 	LIBEVDEVOBJ := 
