--- a/makefile	2025-11-19 22:17:01.808146533 +0200
+++ b/makefile	2025-11-19 22:26:02.705119347 +0200
@@ -182,7 +182,7 @@
 	X11LIB :=
 endif
 
-FSLIB := -lstdc++fs
+FSLIB :=
 
 ifeq ($(MESENOS),osx)
 	LIBEVDEVOBJ := 
@@ -204,8 +204,8 @@
 	cp InteropDLL/$(OBJFOLDER)/$(SHAREDLIB) $(OUTFOLDER)/$(SHAREDLIB)
 	#Called twice because the first call copies native libraries to the bin folder which need to be included in Dependencies.zip
 	#Don't run with AOT flags the first time to reduce build duration
-	cd UI && dotnet publish -c $(BUILD_TYPE) $(OPTIMIZEUI) -r $(MESENPLATFORM)
-	cd UI && dotnet publish -c $(BUILD_TYPE) $(OPTIMIZEUI) $(PUBLISHFLAGS)
+	cd UI && dotnet publish -c $(BUILD_TYPE) $(OPTIMIZEUI) -r $(MESENPLATFORM) --source ../nuget-sources
+	cd UI && dotnet publish -c $(BUILD_TYPE) $(OPTIMIZEUI) $(PUBLISHFLAGS) --source ../nuget-sources
 
 core: InteropDLL/$(OBJFOLDER)/$(SHAREDLIB)
 
